<?php

/**
 * @file
 * Primary module hooks for Chem Inv module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * Implements hook_theme().
 */
function chem_inv_theme($existing, $type, $theme, $path)
{
    return [
        'cheminv-compounds' => [
            'variables' => [
                'compounds' => null,
            ],

        ],
    ];
}
